[[plugins]]
  package = "netlify-plugin-opensearch"
  [plugins.inputs]
    searchUrl = "https://unicode.party/?query="
    searchFile = "opensearch.xml"
    siteShortName = "Unicode Party"
    siteDescription = "Unicode emoji search engine"
